"""empty message

Revision ID: 41f5787ce5a8
Revises: 9785d59cdd8e
Create Date: 2022-04-07 14:39:56.405686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41f5787ce5a8'
down_revision = '9785d59cdd8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('annotations', sa.Column('initialAnnoIndex', sa.Integer(), nullable=True))
    op.add_column('annotations', sa.Column('finalAnnoIndex', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('annotations', 'finalAnnoIndex')
    op.drop_column('annotations', 'initialAnnoIndex')
    # ### end Alembic commands ###
